export const projects = [
  {
    title: "Personalized Health Companion 💪",
    images: ["/projects-gallery/personalized-health-companion.png"],
    techStack: ["React.js", "Node.js", "Express.js", "TailwindCSS", "MongoDB"],
    description: "An AI-driven health assistant that tracks workouts, suggests exercises, and monitors health metrics for better fitness.",
    github: "https://github.com/anmolkhurana490/Personalized-Health-Companion.git",
    demo: "#",
  },
  {
    title: "Yoga Pose Recognition & Correction System 🧘‍♂️",
    images: ["/projects-gallery/ai-yoga-trainer.png"],
    techStack: ["Python", "Tensorflow", "Computer Vision", "JavaScript"],
    description: "A computer vision-based AI trainer that detects yoga poses and provides real-time feedback for correct posture alignment.",
    github: "https://github.com/anmolkhurana490/Yoga-Posture-Recognition-and-Correction-System.git",
    demo: "#",
  },
  {
    title: "Movie Recommendation System 🎬",
    images: ["/projects-gallery/movie-recommendation-system.jpeg"],
    techStack: ["Python", "KNN", "KMeans", "Flask"],
    description: "A machine learning-based system that suggests personalized movie recommendations using KNN and KMeans clustering techniques.",
    github: "https://github.com/anmolkhurana490/Movie-Recommendation-System-.git",
    demo: "#",
  },
  {
    title: "Indian Celebrity Face Classification 👨‍🎤",
    images: ["/projects-gallery/indian-celebrity-face-recognition.png"],
    techStack: ["Python", "OpenCV", , "Scikit-Learn"],
    description: "A deep learning model that classifies Indian celebrities based on facial features using OpenCV and Logistic Regression.",
    github: "https://github.com/anmolkhurana490/Indian-Celebrity-Face-Classification.git",
    demo: "#",
  },
  {
    title: "Fake Product Analysis 🛍️",
    images: ["/projects-gallery/fake-product-analysis.png"],
    techStack: ["ML", "Blockchain", "Flask"],
    description: "A hybrid ML and blockchain-based system to detect and prevent counterfeit products in e-commerce platforms..",
    github: "https://github.com/anmolkhurana490/Fake-product-analysis-using-ML-and-blockchain.git",
    demo: "#",
  },
];